# Default values for drupal projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: draft
  tag: dev
  pullPolicy: IfNotPresent
service:
  name: drupal
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 2
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 768Mi
probePath: /healthz
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
nameOverride: app

mysql:
  mysqlUser: drupal8
  mysqlPassword: drupal8
  mysqlDatabase: drupal8
  fullnameOverride: database